services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:5000/api
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - "8000:8000"
  database:
    image: mysql:8.0.41
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_DB=SampleDB
    ports:
      - "8001:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
